version: '3.8'

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"  # Map port 3000 of the container to port 3000 on your host machine
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    volumes:
      - .:/app  # Bind mount to allow hot reloading during development
    env_file:
      - ./.env  # Use a local .env file for environment variables
    depends_on:
      - supabase

  supabase:
    image: supabase/supabase:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
